help:
	@echo "copy  -  copy bit files from transfer directory to local directory"
	@echo "clean -  tidy up unneeded impact stuff"

clean:
	rm output.txt
	rm -rf *_xdb

copy:
	cp /cygdrive/m/Fwf/4-VHDL-Design/BPM-DCM/transfer/*.bit .

#/cygdrive/m/Fwf/4-VHDL-Design/BPM-DCM/Vogel/aktueller\ Stand\ 30.07.2010/ZPU_System_basis_V4/Hardware/synthese/
