#
# switch your used software here
# this file is used both, by simulation and synthesis
#

target_dir = ethernet_speed

all:
	make --directory $(target_dir)
	cp $(target_dir)/*.elf .

clean:
	rm -f *.elf
