/**************************************************************************
 * 
 *
 * This file was generated by dclib/netpp. Modifications to this file will
 * be lost.
 * Stylesheet: genreg.xsl       (c) 2010-2011 section5
 *
 * Version: 0.0
 **************************************************************************/



#ifndef _BITMASK_
#define _BITMASK_(msb, lsb) ( (-1 << (msb + 1)) ^ (-1 << lsb) )
#endif
#ifndef _BIT_
#define _BIT_(pos) (1 << pos)
#endif



/*********************************************************
 * Address segment 'TAP'
 *********************************************************/
		
#define TAP_IDCODE               0x01
#define TAP_EMUDATA              0x02
#define TAP_EMUCTRL              0x03
#	define EMUREQ                      _BIT_(0)
#	define CORE_RESET                  _BIT_(15)
#define TAP_EMUSTAT              0x04
#	define EMUACK                      _BIT_(0)
#	define EMURDY                      _BIT_(1)
#	define EMUDAT_UNR                  _BIT_(2)
#	define EMUDAT_OVR                  _BIT_(3)
#	define CORE_SPEC                   _BITMASK_(15, 8)
#	define CORE_SPEC_SHFT  8
#define TAP_EMUIR                0x05
#define TAP_DBGPC                0x08
#define TAP_COUNT1               0x0c
#define TAP_COUNT2               0x0d
