/**************************************************************************
 * 
 *
 * This file was generated by dclib/netpp. Modifications to this file will
 * be lost.
 * Stylesheet: genreg.xsl       (c) 2010-2011 section5
 *
 * Version: 0.0
 **************************************************************************/



#ifndef _BITMASK_
#define _BITMASK_(msb, lsb) ( (-1 << (msb + 1)) ^ (-1 << lsb) )
#endif
#ifndef _BIT_
#define _BIT_(pos) (1 << pos)
#endif



/*********************************************************
 * Address segment 'ZPUsmall'
 *********************************************************/
		
#define ZPUsmall_EMUSTAT_DUMMY        0x04
#	define ZPU_IDIM                    _BIT_(15)
#	define ZPU_BREAK                   _BIT_(14)
#	define ZPU_MEMBUSY                 _BIT_(9)
#	define ZPU_INRESET                 _BIT_(8)
